name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get last commit SHA with message "auto commit"
        id: last_commit
        run: |
          LAST_SHA=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=1&q=auto+commit" | \
                        jq -r '.[0].sha')
          echo "::set-output name=sha::$LAST_SHA"
      - name: Get current commit SHA
        id: current_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Check if packages directory is modified
        id: check-packages
        run: |
          # 获取提交的差异代码
          echo "steps.last_commit.outputs.sha: ${{ steps.last_commit.outputs.sha }}"
          echo "steps.current_commit.outputs.sha: ${{ steps.current_commit.outputs.sha }}"
          DIFF_FILES=$(git diff --name-only ${{ steps.last_commit.outputs.sha }} ${{ steps.current_commit.outputs.sha }})
          echo "Diff files: $DIFF_FILES"

          # 检查是否存在packages目录文件的变更
          if echo $DIFF_FILES | grep -qE "packages/*"; then
            echo "Changes found in packages directory"
            echo "::set-output name=should_build::true"
          else
            echo "No changes found in packages directory"
            echo "::set-output name=should_build::false"
          fi
      - name: Install dependencies
        if: steps.check-packages.outputs.should_build == 'true'
        run: npm install
      - name: Build
        if: steps.check-packages.outputs.should_build == 'true'
        run: |
          # 获取提交的差异代码
          DIFF_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "Diff files: $DIFF_FILES"

          # 提取目录名
          DIRS=$(echo $DIFF_FILES | grep -oE "packages/[^/]+(/|$)" | sed 's:/[^/]*$::' | sort -u
          echo "Build directories: $DIRS"

          # 在每个目录下执行npm run build命令
          for DIR in $DIRS; do
            cd $DIR
            echo "Building $DIR..."
            npm run build
            cd -
          done

          # 提交构建产物到dist分支
          git config --global user.email "im.wangzhenxi@gmail.com"
          git config --global user.name "wangzhenxi"
          git fetch origin dist
          git checkout -b dist origin/dist
          git merge --no-commit --no-ff main
          git add -A .
          git commit -m "Build and Deploy"
          git push -u origin dist
